### ISSUE TITLE
I want to use port 6789 instead of port 3000. How should I modify it?

### ISSUE THREAD

**Issue by qlfgggggg** [fboucquez/symbol-bootstrap#352]
I want to use port 6789 instead of port 3000. How should I modify it?

**Comment by fboucquez** [comment]
Add 
```
gateways:
    - openPort: 6789
```
To your `custom-preset.yml`. 

Please notice that HTTP 3000 and HTTPS 3001 are the standard ports for the rest gateway. If you change the port, discovery services like the statistic service may not find your node or think your gateway is down.

**Comment by fboucquez** [comment]
Closing, please reopen if you have issues
